services:
  - type: web
    name: sturum-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI_COMPASS
        sync: false
      - key: SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 10000
